import pygame

WIDTH = 800
HEIGHT = 600
FPS = 60
TITLE = "Beyond the Dome"

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)

PLAYER_COLOR = BLUE
PLAYER_SPEED = 5
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32
PLAYER_HEALTH = 100
PLAYER_INVINCIBILITY_DURATION = 1000

ENEMY_WIDTH = 32
ENEMY_HEIGHT = 32
ENEMY_DETECT_RADIUS = 250
ENEMY_ATTACK_RADIUS = 50
ENEMY_PATROL_RADIUS = 100
ENEMY_ATTACK_COOLDOWN = 1500
ENEMY_SEARCH_DURATION = 5000

ENEMY_RAIDER_COLOR = RED
ENEMY_RAIDER_HEALTH = 75
ENEMY_RAIDER_DAMAGE = 10
ENEMY_RAIDER_SPEED = 2

ENEMY_DOG_COLOR = YELLOW
ENEMY_DOG_HEALTH = 55
ENEMY_DOG_DAMAGE = 5
ENEMY_DOG_SPEED = 3

ITEM_COLOR = GREEN
ITEM_WIDTH = 16
ITEM_HEIGHT = 16

MELEE_WEAPON_RANGE = 50
MELEE_WEAPON_DAMAGE = 20
MELEE_WEAPON_COOLDOWN = 500
MELEE_WEAPON_ANIMATION_DURATION = 200
MELEE_WEAPON_ARC = 90
MELEE_WEAPON_COLOR = YELLOW
MELEE_WEAPON_WIDTH = 40
MELEE_WEAPON_HEIGHT = 5

SLINGSHOT_COLOR = (139, 69, 19)
SLINGSHOT_Y_WIDTH = 20
SLINGSHOT_Y_HEIGHT = 30
SLINGSHOT_HANDLE_HEIGHT = 15
SLINGSHOT_THICKNESS = 4
SLINGSHOT_BAND_COLOR = (40, 40, 40)
SLINGSHOT_COOLDOWN = 600
SLINGSHOT_POWER_MIN = 150
SLINGSHOT_POWER_MAX = 450
SLINGSHOT_CHARGE_TIME = 1000
SLINGSHOT_AIMING_LINE_COLOR = YELLOW

STONE_COLOR = (105, 105, 105) 
STONE_RADIUS = 5
STONE_DAMAGE = 15
STONE_LIFETIME = 2000
STONE_SPEED_MIN = 5
STONE_SPEED_MAX = 15
STONE_INITIAL_COUNT = 15

ENEMY_HEALTH_BAR_WIDTH = 40
ENEMY_HEALTH_BAR_HEIGHT = 5
ENEMY_HEALTH_BAR_OFFSET = 5
ENEMY_HEALTH_BAR_COLOR_MAX = GREEN
ENEMY_HEALTH_BAR_COLOR_MIN = RED
ENEMY_HEALTH_BAR_BACKGROUND_COLOR = DARKGREY
ENEMY_HEALTH_BAR_BORDER_COLOR = WHITE

BLOOD_PARTICLE_COUNT = 5
BLOOD_PARTICLE_SIZE = 2
BLOOD_PARTICLE_SPEED = 2
BLOOD_PARTICLE_LIFETIME = 1000  
BLOOD_PARTICLE_COLOR = RED

TILE_SIZE = 32

FONT_NAME = pygame.font.match_font('arial')
HUD_FONT_SIZE = 25
HUD_COLOR = WHITE
GAME_OVER_FONT_SIZE = 50

HEALTH_BAR_WIDTH = 150
HEALTH_BAR_HEIGHT = 20
HEALTH_BAR_X = 10
HEALTH_BAR_Y = 10
HEALTH_BAR_COLOR_MAX = GREEN
HEALTH_BAR_COLOR_MIN = RED
HEALTH_BAR_BACKGROUND_COLOR = DARKGREY
HEALTH_BAR_BORDER_COLOR = WHITE 